### ISSUE TITLE
viv.geo depreciated?

### ISSUE THREAD

**Issue by error404notfound** [bixbydevelopers/capsule-sample-space-resorts#1]
Hi there! 

I am working my way through this capsule, With the 6.2.0-rc.5485   version I get deprecated warnings, where do I go to find out what replaces the depreciated things? I am more than happy to help make the changes to the sample to bring it up to date.

**Comment by sarahmolinerroy** [comment]
Hi @error404notfound,

The list of recommended library capsule versions to use is posted here: https://bixbydevelopers.com/dev/docs/dev-guide/developers/library

For example, at time of writing `viv.geo:9.15.0` is the recommended version and it is not deprecated.

You can safely ignore any warnings (yellow) from those libraries. If these were errors (red), then an update would be required.

This is great feedback and we will work on updating the UX to make the distinction clearer.

Keep up the great work!
